import { auditChange, defaultPreferences, DemoError, memberFor, membersForOrganization, paginate, permissionFor, type AuditEvent, type DemoState, type FileRecord, type ListQuery, type MemberUser, type Membership, type Notification, type Organization, type PageResult, type Permission, type Preferences, type Role, type User } from "./demo";
import { isAccentColor } from "./appearance";

export type UserQuery = ListQuery & { organizationId: string; roleId?: string; status?: Membership["status"] };
export type UserInput = { id?: string; organizationId: string; name: string; email: string; roleId: string };
export type MockService = {
  listUsers(query: UserQuery): Promise<PageResult<MemberUser>>;
  saveUser(input: UserInput): Promise<MemberUser>;
  changeUserStatus(organizationId: string, ids: string[]): Promise<void>;
  listRoles(organizationId: string): Promise<Role[]>;
  createRole(organizationId: string, name: string): Promise<Role>;
  setRolePermission(organizationId: string, roleId: string, code: Permission, enabled: boolean): Promise<void>;
  listFiles(organizationId: string, query?: ListQuery & { mimeType?: string }): Promise<PageResult<FileRecord>>;
  addFile(organizationId: string, file: Pick<FileRecord, "name" | "mimeType" | "size">): Promise<FileRecord>;
  renameFile(organizationId: string, id: string, name: string): Promise<void>;
  deleteFile(organizationId: string, id: string): Promise<void>;
  listNotifications(organizationId: string): Promise<Notification[]>;
  markNotifications(organizationId: string, ids: string[]): Promise<void>;
  listAudit(organizationId: string, query?: ListQuery): Promise<PageResult<AuditEvent>>;
  updateOrganization(organizationId: string, change: Partial<Pick<Organization, "name" | "currency" | "timezone" | "color" | "enabledModules" | "logoLight" | "logoDark" | "logoCompact" | "favicon">>): Promise<void>;
  addBranch(organizationId: string, name: string): Promise<void>;
  updateBranch(organizationId: string, id: string, change: { name: string; address: string; status: "Activa" | "Inactiva" }): Promise<void>;
  updatePreferences(organizationId: string, change: Partial<Preferences>): Promise<void>;
  updateProfile(change: Partial<Pick<User, "name" | "avatar">>): Promise<void>;
};

export function createMockService(read: () => DemoState, write: (action: (draft: DemoState) => void) => void): MockService {
  async function delay() { const state = read(); await new Promise((resolve) => setTimeout(resolve, state.latency)); if (state.scenario === "error") throw new DemoError("SERVICE", "No se pudieron cargar los datos de demostración."); }
  function guard(organizationId: string, permission?: Permission) { const state = read(); if (organizationId !== state.organizationId || memberFor(state, state.accountId, organizationId)?.status !== "Activo" || permission && !permissionFor(state, permission)) throw new DemoError("DENIED", "No tienes permiso para esta operación."); return state; }
  function activeAdminCount(state: DemoState, organizationId: string) { return state.memberships.filter((item) => item.organizationId === organizationId && item.status === "Activo" && state.roles.find((role) => role.id === item.roleId)?.name === "Administrador").length; }
  return {
    async listUsers(query) { guard(query.organizationId, "users.read"); await delay(); const state = read(); if (state.scenario === "vacío") return paginate([], query); const term = query.search?.trim().toLocaleLowerCase("es") ?? ""; const items = membersForOrganization(state, query.organizationId).filter((item) => (!term || (item.name + item.email).toLocaleLowerCase("es").includes(term)) && (!query.roleId || item.roleId === query.roleId) && (!query.status || item.status === query.status)).sort((a, b) => (query.sort === "desc" ? -1 : 1) * a.name.localeCompare(b.name, "es")); return paginate(items, query); },
    async saveUser(input) {
      guard(input.organizationId, input.id ? "users.update" : "users.create"); await delay(); const state = read();
      if (typeof input.name !== "string" || typeof input.email !== "string" || typeof input.roleId !== "string") throw new DemoError("VALIDATION", "Introduce nombre, correo y rol válidos.");
      const name = input.name.trim(), email = input.email.trim().toLowerCase();
      if (!name || name.length > 120 || email.length > 254 || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) throw new DemoError("VALIDATION", "Introduce nombre y correo válidos.");
      if (state.users.some((item) => item.email.toLowerCase() === email && item.id !== input.id)) throw new DemoError("VALIDATION", "El correo ya pertenece a otra cuenta.");
      if (!state.roles.some((role) => role.id === input.roleId && role.organizationId === input.organizationId)) throw new DemoError("VALIDATION", "Selecciona un rol válido.");
      const existing = input.id ? membersForOrganization(state, input.organizationId).find((item) => item.id === input.id) : undefined;
      if (input.id && !existing) throw new DemoError("NOT_FOUND", "Usuario inexistente.");
      if (existing && !permissionFor(state, "roles.manage") && (existing.roleId !== input.roleId || state.roles.find((role) => role.id === existing.roleId)?.name === "Administrador")) throw new DemoError("DENIED", "No puedes editar este usuario o su rol.");
      const removingAdmin = existing?.status === "Activo" && state.roles.find((role) => role.id === existing.roleId)?.name === "Administrador" && state.roles.find((role) => role.id === input.roleId)?.name !== "Administrador";
      if (removingAdmin && activeAdminCount(state, input.organizationId) <= 1) throw new DemoError("VALIDATION", "Debe quedar al menos un administrador activo.");
      const user: User = existing ? { id: existing.id, name, email, avatar: existing.avatar, createdAt: existing.createdAt } : { id: crypto.randomUUID(), name, email, createdAt: new Date().toISOString() };
      write((draft) => { const index = draft.users.findIndex((item) => item.id === user.id); if (index >= 0) draft.users[index] = user; else { draft.users.push(user); draft.memberships.push({ id: crypto.randomUUID(), organizationId: input.organizationId, userId: user.id, roleId: input.roleId, status: "Activo" }); } const membership = memberFor(draft, user.id, input.organizationId)!; membership.roleId = input.roleId; auditChange(draft, "usuarios", existing ? "editar" : "crear", user.id, existing ?? null, { ...user, organizationId: input.organizationId, roleId: membership.roleId, status: membership.status }); });
      return { ...user, organizationId: input.organizationId, roleId: input.roleId, status: existing?.status ?? "Activo" };
    },
    async changeUserStatus(organizationId, ids) { guard(organizationId, "users.deactivate"); await delay(); const state = read(); const members = ids.map((id) => memberFor(state, id, organizationId)); if (members.some((item) => !item)) throw new DemoError("NOT_FOUND", "Usuario inexistente."); const deactivatedAdmins = members.filter((item) => item?.status === "Activo" && state.roles.find((role) => role.id === item.roleId)?.name === "Administrador").length; if (activeAdminCount(state, organizationId) - deactivatedAdmins < 1) throw new DemoError("VALIDATION", "Debe quedar al menos un administrador activo."); write((draft) => { for (const id of ids) { const target = memberFor(draft, id, organizationId)!; const before = { ...target }; target.status = target.status === "Activo" ? "Inactivo" : "Activo"; auditChange(draft, "usuarios", "estado", id, before, target); } }); },
    async listRoles(organizationId) { guard(organizationId, "roles.manage"); await delay(); if (read().scenario === "vacío") return []; return read().roles.filter((item) => item.organizationId === organizationId); },
    async createRole(organizationId, name) { guard(organizationId, "roles.manage"); await delay(); const state = read(); const value = name.trim(); if (!value || state.roles.some((item) => item.organizationId === organizationId && item.name.toLocaleLowerCase("es") === value.toLocaleLowerCase("es"))) throw new DemoError("VALIDATION", "Introduce un nombre de rol único."); const role: Role = { id: crypto.randomUUID(), organizationId, name: value, permissions: [], protected: false }; write((draft) => { draft.roles.push(role); auditChange(draft, "roles", "crear", role.id, null, role); }); return role; },
    async setRolePermission(organizationId, roleId, code, enabled) { guard(organizationId, "roles.manage"); await delay(); const state = read(); const role = state.roles.find((item) => item.id === roleId && item.organizationId === organizationId); if (!role) throw new DemoError("NOT_FOUND", "Rol inexistente."); if (role.protected) throw new DemoError("DENIED", "El rol administrador base está protegido."); if (enabled && !permissionFor(state, code)) throw new DemoError("DENIED", "No puedes conceder permisos que no posees."); write((draft) => { const target = draft.roles.find((item) => item.id === roleId)!; const before = [...target.permissions]; target.permissions = enabled ? [...new Set([...before, code])] : before.filter((item) => item !== code); auditChange(draft, "roles", "editar", roleId, before, target.permissions); }); },
    async listFiles(organizationId, query = {}) { guard(organizationId, "files.read"); await delay(); if (read().scenario === "vacío") return paginate([], query); const term = query.search?.toLocaleLowerCase("es") ?? ""; const items = read().files.filter((item) => item.organizationId === organizationId && item.name.toLocaleLowerCase("es").includes(term) && (!query.mimeType || item.mimeType === query.mimeType)); return paginate(items, query); },
    async addFile(organizationId, file) { guard(organizationId, "files.manage"); await delay(); if (!file.name.trim() || file.size > 5 * 1024 * 1024) throw new DemoError("VALIDATION", "Selecciona un archivo de hasta 5 MB."); const record: FileRecord = { id: crypto.randomUUID(), organizationId, name: file.name, mimeType: file.mimeType, size: file.size, ownerId: read().accountId!, createdAt: new Date().toISOString() }; write((draft) => { draft.files.push(record); auditChange(draft, "archivos", "registrar", record.id, null, record); }); return record; },
    async renameFile(organizationId, id, name) { guard(organizationId, "files.manage"); await delay(); if (!name.trim()) throw new DemoError("VALIDATION", "Introduce un nombre."); if (!read().files.some((item) => item.id === id && item.organizationId === organizationId)) throw new DemoError("NOT_FOUND", "Archivo inexistente."); write((draft) => { const target = draft.files.find((item) => item.id === id && item.organizationId === organizationId)!; const before = target.name; target.name = name.trim(); auditChange(draft, "archivos", "renombrar", id, before, target.name); }); },
    async deleteFile(organizationId, id) { guard(organizationId, "files.manage"); await delay(); if (!read().files.some((item) => item.id === id && item.organizationId === organizationId)) throw new DemoError("NOT_FOUND", "Archivo inexistente."); write((draft) => { const target = draft.files.find((item) => item.id === id && item.organizationId === organizationId)!; draft.files = draft.files.filter((item) => item.id !== id); auditChange(draft, "archivos", "eliminar", id, target, null); }); },
    async listNotifications(organizationId) { guard(organizationId); await delay(); if (read().scenario === "vacío") return []; return read().notifications.filter((item) => item.organizationId === organizationId && item.userId === read().accountId); },
    async markNotifications(organizationId, ids) { guard(organizationId); await delay(); write((draft) => { for (const item of draft.notifications) if (item.organizationId === organizationId && item.userId === draft.accountId && ids.includes(item.id)) item.readAt = new Date().toISOString(); }); },
    async listAudit(organizationId, query = {}) { guard(organizationId, "audit.read"); await delay(); if (read().scenario === "vacío") return paginate([], query); return paginate(read().audit.filter((item) => item.organizationId === organizationId), query); },
    async updateOrganization(organizationId, changes) { const safe = Object.fromEntries(Object.entries(changes).filter(([key]) => ["name", "currency", "timezone", "color", "enabledModules", "logoLight", "logoDark", "logoCompact", "favicon"].includes(key))) as typeof changes; guard(organizationId, Object.keys(safe).every((key) => key === "name") ? "organization.manage" : "settings.manage"); await delay(); if (safe.name !== undefined && (typeof safe.name !== "string" || !safe.name.trim() || safe.name.length > 120)) throw new DemoError("VALIDATION", "Introduce un nombre de empresa de hasta 120 caracteres."); if (safe.currency !== undefined && (typeof safe.currency !== "string" || !/^[A-Z]{3}$/.test(safe.currency))) throw new DemoError("VALIDATION", "Moneda inválida."); if (safe.color !== undefined && !isAccentColor(safe.color)) throw new DemoError("VALIDATION", "Color inválido."); for (const key of ["logoLight", "logoDark", "logoCompact", "favicon"] as const) { const image = safe[key]; if (image !== undefined && (typeof image !== "string" || image.length > 3_000_000 || !/^data:image\/(png|jpeg|webp);base64,/.test(image))) throw new DemoError("VALIDATION", "Imagen inválida o demasiado grande."); } if (safe.enabledModules && (!Array.isArray(safe.enabledModules) || ["dashboard", "roles", "organization", "settings", "notifications", "profile"].some((id) => !safe.enabledModules?.includes(id as Organization["enabledModules"][number])))) throw new DemoError("VALIDATION", "No se pueden deshabilitar módulos esenciales."); if (safe.timezone) { try { if (safe.timezone.length > 100) throw new Error("longitud"); new Intl.DateTimeFormat("es-BO", { timeZone: safe.timezone }); } catch { throw new DemoError("VALIDATION", "Zona horaria inválida."); } } write((draft) => { const target = draft.organizations.find((item) => item.id === organizationId); if (!target) throw new DemoError("NOT_FOUND", "Empresa inexistente."); const before = { ...target }; Object.assign(target, safe); auditChange(draft, "configuración", "editar", organizationId, before, target); }); },
    async addBranch(organizationId, name) { guard(organizationId, "organization.manage"); await delay(); if (!name.trim()) throw new DemoError("VALIDATION", "Introduce un nombre de sucursal."); write((draft) => { const target = draft.organizations.find((item) => item.id === organizationId)!; const branch = { id: crypto.randomUUID(), name: name.trim(), address: "", status: "Activa" as const }; target.branches.push(branch); auditChange(draft, "empresa", "crear sucursal", branch.id, null, branch); }); },
    async updateBranch(organizationId, id, changes) { guard(organizationId, "organization.manage"); await delay(); if (typeof changes.name !== "string" || !changes.name.trim() || typeof changes.address !== "string" || !["Activa", "Inactiva"].includes(changes.status)) throw new DemoError("VALIDATION", "Revisa los datos de la sucursal."); if (!read().organizations.find((item) => item.id === organizationId)?.branches.some((item) => item.id === id)) throw new DemoError("NOT_FOUND", "Sucursal inexistente."); write((draft) => { const target = draft.organizations.find((item) => item.id === organizationId)!.branches.find((item) => item.id === id)!; const before = { ...target }; Object.assign(target, { name: changes.name.trim(), address: changes.address.trim(), status: changes.status }); auditChange(draft, "empresa", "editar sucursal", id, before, target); }); },
    async updatePreferences(organizationId, changes) { guard(organizationId); await delay(); const safe = Object.fromEntries(Object.entries(changes).filter(([key]) => ["theme", "accentLight", "accentDark", "locale", "density", "favorites", "tableColumns", "notificationChannels", "notificationCategories"].includes(key))) as Partial<Preferences>; if (safe.theme && !["light", "dark", "system"].includes(safe.theme)) throw new DemoError("VALIDATION", "Tema inválido."); if (safe.density && !["Cómoda", "Compacta"].includes(safe.density)) throw new DemoError("VALIDATION", "Densidad inválida."); if (safe.locale && !["es-BO", "es-ES"].includes(safe.locale)) throw new DemoError("VALIDATION", "Idioma inválido."); if (safe.notificationChannels !== undefined && (typeof safe.notificationChannels !== "object" || safe.notificationChannels === null || typeof safe.notificationChannels.panel !== "boolean" || typeof safe.notificationChannels.correo !== "boolean")) throw new DemoError("VALIDATION", "Canales de notificación inválidos."); if (safe.notificationCategories !== undefined && (typeof safe.notificationCategories !== "object" || safe.notificationCategories === null || typeof safe.notificationCategories.actividad !== "boolean" || typeof safe.notificationCategories.sistema !== "boolean")) throw new DemoError("VALIDATION", "Categorías de notificación inválidas."); write((draft) => { const key = `${draft.accountId}:${organizationId}`; const before = draft.preferences[key] ?? null; draft.preferences[key] = { ...(before ?? defaultPreferences()), ...safe }; auditChange(draft, "preferencias", "editar", draft.accountId!, before, draft.preferences[key]); }); },
    async updateProfile(changes) { const state = read(); guard(state.organizationId); await delay(); if (changes.name !== undefined && (typeof changes.name !== "string" || !changes.name.trim() || changes.name.length > 120)) throw new DemoError("VALIDATION", "Introduce un nombre de hasta 120 caracteres."); if (changes.avatar !== undefined && (typeof changes.avatar !== "string" || changes.avatar.length > 3_000_000 || !/^data:image\/(png|jpeg|webp);base64,/.test(changes.avatar))) throw new DemoError("VALIDATION", "Avatar inválido o demasiado grande."); const safe = { ...(changes.name !== undefined ? { name: changes.name.trim() } : {}), ...(typeof changes.avatar === "string" ? { avatar: changes.avatar } : {}) }; write((draft) => { const target = draft.users.find((item) => item.id === draft.accountId); if (!target) throw new DemoError("NOT_FOUND", "Cuenta inexistente."); const before = { ...target }; Object.assign(target, safe); auditChange(draft, "perfil", "editar", target.id, before, target); }); },
  };
}
