"use client";

import { useState } from "react";
import { useTheme } from "next-themes";
import { AppearanceSettings } from "@/components/appearance-settings";
import { useDemo } from "@/components/demo-provider";
import { Card, PageHeading } from "@/components/ui";
import { accentChoices } from "@/lib/appearance";
import { defaultPreferences, modules, permissionFor, visibleModule, type Preferences } from "@/lib/demo";

const field = "w-full rounded-lg border border-border bg-surface px-3 py-2 text-foreground";
const action = "rounded-lg border border-border px-3 py-2 text-sm";
export function SettingsSection() {
  const { state, service, setDirty } = useDemo();
  const { setTheme } = useTheme();
  const org = state.organizations.find((item) => item.id === state.organizationId)!;
  const [tab, setTab] = useState("Identidad visual");
  const [name, setName] = useState(org.name);
  const [color, setColor] = useState(org.color);
  const [currency, setCurrency] = useState(org.currency);
  const [timezone, setTimezone] = useState(org.timezone);
  const [message, setMessage] = useState("");
  const canManage = permissionFor(state, "settings.manage");
  async function savePreference(changes: Partial<Preferences>) { try { await service.updatePreferences(org.id, changes); setMessage("Preferencia guardada."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo guardar."); } }
  async function saveBrand() { try { await service.updateOrganization(org.id, { name, color }); setDirty(false); setMessage("Identidad visual guardada."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo guardar."); } }
  async function saveRegion() { try { await service.updateOrganization(org.id, { currency: currency.toUpperCase(), timezone }); setDirty(false); setMessage("Preferencias regionales guardadas."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo guardar."); } }
  function upload(key: "logoLight" | "logoDark" | "logoCompact" | "favicon", file?: File) { if (!file || !canManage) return; if (!(["image/png", "image/jpeg", "image/webp"].includes(file.type)) || file.size > 2 * 1024 * 1024) { setMessage("Selecciona PNG, JPEG o WebP de hasta 2 MB."); return; } const reader = new FileReader(); reader.onload = async () => { const value = reader.result; if (typeof value !== "string") return; try { await service.updateOrganization(org.id, { [key]: value }); setMessage("Imagen guardada."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo guardar la imagen."); } }; reader.onerror = () => setMessage("No se pudo leer la imagen."); reader.readAsDataURL(file); }
  const prefKey = `${state.accountId}:${org.id}`;
  return <><PageHeading eyebrow="Personalización" title="Configuración" description="Configuración de la empresa y preferencias personales." />
    <div role="tablist" aria-label="Secciones de configuración" className="mb-5 flex flex-wrap gap-2">{["Identidad visual", "Regional", "Módulos", "Preferencias"].map((item) => <button key={item} role="tab" aria-selected={tab === item} className={`${action} ${tab === item ? "bg-accent-soft text-accent-text" : ""}`} onClick={() => setTab(item)}>{item}</button>)}</div>
    {message && <p role="status" className="mb-4 rounded-lg bg-accent-soft p-3 text-sm text-accent-text">{message}</p>}
    {tab === "Identidad visual" && <div className="space-y-5"><Card className="grid gap-4 p-5 sm:grid-cols-2"><label className="text-sm">Nombre del sistema<input className={field} value={name} disabled={!canManage} onChange={(event) => { setName(event.target.value); setDirty(true); }} /></label><label className="text-sm">Color principal<select className={field} value={color} disabled={!canManage} onChange={(event) => { setColor(event.target.value); setDirty(true); }}>{accentChoices.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="sm:col-span-2"><p className="text-sm font-semibold">Vista previa</p><div className="mt-2 rounded-xl border border-border bg-surface-muted p-5"><span className="font-bold">{name || org.name}</span><span className="ml-3 rounded-lg bg-accent-soft px-3 py-1 text-accent-text">{accentChoices.find((item) => item.id === color)?.name}</span></div></div>{canManage && <button className={action} onClick={saveBrand}>Guardar identidad</button>}</Card><Card className="grid gap-4 p-5 sm:grid-cols-2">{(["logoLight", "logoDark", "logoCompact", "favicon"] as const).map((key) => <label key={key} className="text-sm">{({ logoLight: "Logo claro", logoDark: "Logo oscuro", logoCompact: "Logo compacto", favicon: "Favicon" })[key]}<input className={field} type="file" accept="image/png,image/jpeg,image/webp" disabled={!canManage} onChange={(event) => upload(key, event.target.files?.[0])} />{org[key] && <img alt={`Vista previa de ${key}`} src={org[key]} className="mt-2 size-12 object-contain" />}</label>)}</Card><AppearanceSettings /></div>}
    {tab === "Regional" && <Card className="grid gap-4 p-5 sm:grid-cols-2"><label className="text-sm">Moneda<input className={field} value={currency} disabled={!canManage} maxLength={3} onChange={(event) => { setCurrency(event.target.value); setDirty(true); }} /></label><label className="text-sm">Zona horaria<input className={field} value={timezone} disabled={!canManage} onChange={(event) => { setTimezone(event.target.value); setDirty(true); }} /></label><p className="text-sm text-muted sm:col-span-2">Fecha inicial: dd/MM/yyyy</p>{canManage && <button className={action} onClick={saveRegion}>Guardar regional</button>}</Card>}
    {tab === "Módulos" && <Card className="space-y-3 p-5">{modules.map((item) => <label key={item.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={org.enabledModules.includes(item.id)} disabled={item.essential || !canManage} onChange={async () => { const enabledModules = org.enabledModules.includes(item.id) ? org.enabledModules.filter((id) => id !== item.id) : [...org.enabledModules, item.id]; try { await service.updateOrganization(org.id, { enabledModules }); setMessage("Módulos actualizados."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo actualizar."); } }} />{item.label}{item.essential && " · Esencial"}</label>)}</Card>}
    {tab === "Preferencias" && <Card className="grid gap-4 p-5 sm:grid-cols-2"><label className="text-sm">Tema<select className={field} value={state.preferences[prefKey]?.theme ?? "system"} onChange={(event) => { const theme = event.target.value as "system" | "light" | "dark"; setTheme(theme); savePreference({ theme }); }}><option value="system">Automático</option><option value="light">Claro</option><option value="dark">Oscuro</option></select></label><label className="text-sm">Densidad de tablas<select className={field} value={state.preferences[prefKey]?.density ?? "Cómoda"} onChange={(event) => savePreference({ density: event.target.value as "Cómoda" | "Compacta" })}><option>Cómoda</option><option>Compacta</option></select></label><div className="sm:col-span-2"><h2 className="mb-2 font-semibold">Accesos favoritos</h2><div className="flex flex-wrap gap-3">{modules.filter((item) => item.id !== "dashboard" && visibleModule(state, item.id)).map((item) => <label key={item.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={state.preferences[prefKey]?.favorites.includes(item.id) ?? false} onChange={(event) => { const favorites = state.preferences[prefKey]?.favorites ?? []; savePreference({ favorites: event.target.checked ? [...favorites, item.id] : favorites.filter((id) => id !== item.id) }); }} />{item.label}</label>)}</div></div></Card>}
    {tab === "Preferencias" && <Card className="mt-4 p-5"><h2 className="font-semibold">Columnas de usuarios</h2><div className="mt-3 flex flex-wrap gap-4">{([ ["role", "Rol"], ["status", "Estado"], ["date", "Fecha"] ] as const).map(([id, label]) => <label key={id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={(state.preferences[prefKey]?.tableColumns ?? ["role", "status", "date"]).includes(id)} onChange={(event) => { const columns = state.preferences[prefKey]?.tableColumns ?? defaultPreferences().tableColumns; savePreference({ tableColumns: event.target.checked ? [...columns, id] : columns.filter((item) => item !== id) }); }} />{label}</label>)}</div></Card>}
    {tab === "Preferencias" && <Card className="mt-4 p-5"><label className="text-sm">Idioma inicial<select className={field} value={state.preferences[prefKey]?.locale ?? "es-BO"} onChange={(event) => savePreference({ locale: event.target.value })}><option value="es-BO">Español (Bolivia)</option><option value="es-ES">Español (España)</option></select></label><p className="mt-2 text-xs text-muted">La interfaz permanece en español.</p></Card>}
  </>;
}
