"use client";

import { useEffect, useMemo, useState } from "react";
import { useDemo } from "@/components/demo-provider";
import { AccountAccess } from "@/components/account-access";
import { Modal } from "@/components/modal";
import { Avatar, Badge, Card, PageHeading } from "@/components/ui";
import { membersForOrganization, permissionFor, type MemberUser, type PageResult } from "@/lib/demo";

const field = "w-full rounded-lg border border-border bg-surface px-3 py-2 text-foreground";
export function UsersView() {
  const { state, service, refresh, dirty, setDirty } = useDemo(); const org = state.organizationId;
  const [query, setQuery] = useState(""); const [role, setRole] = useState(""); const [status, setStatus] = useState(""); const [sort, setSort] = useState<"asc" | "desc">("asc"); const [page, setPage] = useState(1); const [selected, setSelected] = useState<string[]>([]); const [editing, setEditing] = useState<MemberUser | null>(null); const [creating, setCreating] = useState(false); const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<PageResult<MemberUser> | null>(null);
  useEffect(() => { setSelected([]); setPage(1); setEditing(null); setCreating(false); setDirty(false); }, [org, setDirty]);
  useEffect(() => { let active = true; setLoading(true); service.listUsers({ organizationId: org, search: query, roleId: role || undefined, status: status as MemberUser["status"] || undefined, sort, page, pageSize: 8 }).then((value) => { if (active) { setResult(value); setError(""); } }).catch((cause) => { if (active) { setResult(null); setError(cause instanceof Error ? cause.message : "No se pudieron cargar los usuarios."); } }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [service, org, query, role, status, sort, page, state.scenario, state.latency, state.users, state.memberships]);
  const roles = state.roles.filter((item) => item.organizationId === org);
  const filtered = useMemo(() => membersForOrganization(state, org).filter((item) => (item.name + item.email).toLocaleLowerCase("es").includes(query.toLocaleLowerCase("es")) && (!role || item.roleId === role) && (!status || item.status === status)).sort((a, b) => sort === "asc" ? a.name.localeCompare(b.name, "es") : b.name.localeCompare(a.name, "es")), [state, org, query, role, status, sort]);
  const shown = result?.items ?? []; const compact = state.preferences[`${state.accountId}:${org}`]?.density === "Compacta"; const columns = state.preferences[`${state.accountId}:${org}`]?.tableColumns ?? ["role", "status", "date"]; const canCreate = permissionFor(state, "users.create"); const canUpdate = permissionFor(state, "users.update"); const canDeactivate = permissionFor(state, "users.deactivate"); const canExport = permissionFor(state, "users.export");
  async function save(form: FormData) {
    try { await service.saveUser({ id: editing?.id, organizationId: org, name: String(form.get("name") ?? ""), email: String(form.get("email") ?? ""), roleId: String(form.get("role") ?? "") }); setEditing(null); setCreating(false); setDirty(false); setError(""); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo guardar el usuario."); }
  }
  async function deactivate(ids: string[]) {
    if (!window.confirm(`¿Cambiar el estado de ${ids.length} usuario(s)?`)) return;
    try { await service.changeUserStatus(org, ids); setSelected([]); setError(""); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo cambiar el estado."); }
  }
  function closeEditor() { if (dirty && !window.confirm("Hay cambios sin guardar. ¿Descartarlos?")) return; setEditing(null); setCreating(false); setDirty(false); }
  function exportCsv() { if (!canExport) return; const escape = (value: string) => `"${value.replaceAll('"', '""')}"`; const content = ["Nombre,Correo,Rol,Estado", ...filtered.map((item) => [item.name, item.email, roles.find((r) => r.id === item.roleId)?.name ?? "", item.status].map(escape).join(","))].join("\r\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob(["\uFEFF", content], { type: "text/csv;charset=utf-8" })); link.download = `usuarios-${org}.csv`; link.click(); URL.revokeObjectURL(link.href); }
  return <><PageHeading eyebrow="Gestión" title="Usuarios" description="Usuarios de la empresa seleccionada." aside={<div className="flex gap-2">{canExport && <button className="rounded-lg border border-border px-3 py-2 text-sm" onClick={exportCsv}>Exportar CSV</button>}{canCreate && <button className="rounded-lg bg-accent px-3 py-2 text-sm font-semibold text-background" onClick={() => { setDirty(false); setCreating(true); }}>Crear usuario</button>}</div>} />
    {error && <p role="alert" className="mb-4 rounded-lg bg-surface-muted p-3 text-sm">{error}</p>}<Card className="p-4 sm:p-6"><div className="grid gap-3 sm:grid-cols-4"><label className="text-sm">Buscar<input className={field} value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder="Nombre o correo" /></label><label className="text-sm">Rol<select className={field} value={role} onChange={(e) => { setRole(e.target.value); setPage(1); }}><option value="">Todos</option>{roles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm">Estado<select className={field} value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">Todos</option><option>Activo</option><option>Inactivo</option></select></label><label className="text-sm">Orden<select className={field} value={sort} onChange={(e) => setSort(e.target.value as "asc" | "desc")}><option value="asc">Nombre A–Z</option><option value="desc">Nombre Z–A</option></select></label></div><p className="mt-4 text-sm text-muted">{result?.total ?? 0} resultados</p>{canDeactivate && selected.length > 0 && <button className="mt-2 rounded-lg border border-border px-3 py-2 text-sm" onClick={() => deactivate(selected)}>Cambiar estado de {selected.length}</button>}
    {loading ? <p role="status" className="py-12 text-center text-muted">Cargando usuarios…</p> : error ? <div role="alert" className="py-12 text-center"><p>No se pudieron cargar los usuarios.</p><button className="mt-2 text-accent-text underline" onClick={() => void refresh()}>Reintentar</button></div> : shown.length === 0 ? <p className="py-12 text-center text-muted">No se encontraron usuarios.</p> : <div className="mt-4 overflow-x-auto"><table className={`w-full min-w-[650px] text-left text-sm ${compact ? "demo-table-compact" : ""}`}><thead><tr className="border-b border-border text-muted">{canDeactivate && <th className="p-3">Elegir</th>}<th className="p-3">Usuario</th>{columns.includes("role") && <th className="p-3">Rol</th>}{columns.includes("status") && <th className="p-3">Estado</th>}{columns.includes("date") && <th className="p-3">Fecha</th>}<th className="p-3">Acciones</th></tr></thead><tbody>{shown.map((item) => <tr key={item.id} className="border-b border-border">{canDeactivate && <td className="p-3"><input aria-label={`Seleccionar ${item.name}`} type="checkbox" checked={selected.includes(item.id)} onChange={(e) => setSelected(e.target.checked ? [...selected, item.id] : selected.filter((id) => id !== item.id))} /></td>}<td className="p-3"><div className="flex items-center gap-2"><Avatar name={item.name} /><span><strong className="block">{item.name}</strong><small className="text-muted">{item.email}</small></span></div></td>{columns.includes("role") && <td className="p-3">{roles.find((r) => r.id === item.roleId)?.name}</td>}{columns.includes("status") && <td className="p-3"><Badge active={item.status === "Activo"} /></td>}{columns.includes("date") && <td className="p-3">{new Intl.DateTimeFormat("es-BO", { timeZone: state.organizations.find((company) => company.id === org)?.timezone ?? "America/La_Paz" }).format(new Date(item.createdAt))}</td>}<td className="p-3"><div className="flex gap-2"><button className="text-accent-text underline" onClick={() => { setDirty(false); setEditing(item); }}>{canUpdate ? "Editar" : "Ver"}</button>{canDeactivate && <button className="text-accent-text underline" onClick={() => deactivate([item.id])}>{item.status === "Activo" ? "Desactivar" : "Activar"}</button>}</div></td></tr>)}</tbody></table></div>}
    <div className="mt-4 flex items-center justify-between text-sm"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><span>Página {page} de {Math.max(1, Math.ceil((result?.total ?? 0) / 8))}</span><button disabled={page * 8 >= (result?.total ?? 0)} onClick={() => setPage(page + 1)}>Siguiente</button></div></Card>
    {(editing || creating) && <Modal titleId="user-dialog-title" onClose={closeEditor}><h2 id="user-dialog-title" className="text-xl font-bold">{editing ? canUpdate ? "Editar usuario" : "Detalle de usuario" : "Crear usuario"}</h2><form action={save} onInput={() => setDirty(true)} className="mt-4 space-y-3"><label className="block text-sm">Nombre<input name="name" autoFocus className={field} defaultValue={editing?.name} disabled={!!editing && !canUpdate} required /></label><label className="block text-sm">Correo<input name="email" type="email" className={field} defaultValue={editing?.email} disabled={!!editing && !canUpdate} required /></label><label className="block text-sm">Rol<select name="role" className={field} defaultValue={editing?.roleId ?? roles[2]?.id} disabled={!permissionFor(state, "roles.manage")}>{roles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{!permissionFor(state, "roles.manage") && <input type="hidden" name="role" value={editing?.roleId ?? roles[2]?.id} />}</label><div className="flex justify-end gap-3 pt-3"><button type="button" onClick={closeEditor} className="rounded-lg border border-border px-3 py-2">Cerrar</button>{(!editing || canUpdate) && <button className="rounded-lg bg-accent px-3 py-2 text-background">Guardar</button>}</div></form>{editing && permissionFor(state, "roles.manage") && <AccountAccess userId={editing.id} />}</Modal>}
  </>;
}
